# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 153f87bfe89004e54e445af791fb41f197fa42455fca67383432ee1c832781686d0382eeaa8255539a4cfc09d9f75b5b80cf56f0a8b5cbbb6b100496d543ca03

test:
  secret_key_base: 96efe9e801255f75113bab5ec4e731abac3d1a12649b5872ddfb216c0d6269f70050ba4f146e1b5cf143098204cb1eb34e18e19458bf454094d7e52b9c639a32

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
